#!/usr/bin/env python3
import socket
from clr import merah, putih

try:
    socket.create_connection(("8.8.8.8", 50))
      
except OSError:
    print(f"{putih} tidak dapat terhubung ke internet {merah}!! ")
